### PR TITLE
feat: information panels for multiple connections

### PR DESCRIPTION
**Pull request by paula-stacho**
## Description

Looks like more changes than it is, mainly copying and moving stuff.

Changes in nutshell:
- added the 2 info panels with updated design to connection-form, behind multiple connections feature toggle
- the original info panels are hidden when the toggle is on
- separated atlas-help to make future changes & cleanup easier, as this will be the only one of the original 'form-help' that remains in the welcome screen (might be completely useless if we don't stay within compass-connections)

### Checklist
- [x] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [x] New feature
- [ ] Dependency update
- [ ] Misc

## Types of changes

- [ ] *Backport Needed*
- [ ] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by himanshusinghs — APPROVED** [review]
Noice, looks great 🚀

**Comment by kmruiz** [comment]
Screenshot 2024-03-12 at 11 23 47

This info box is visible in the initial screen with the toggle on, should this be hidden when the multiple connections toggle is on?

**Review by kmruiz — APPROVED** [review]
I think it's great, I'm approving the PR because there is only one thing that I don't think it's blocker.

**Comment by paula-stacho** [comment]
> Screenshot 2024-03-12 at 11 23 47
> This info box is visible in the initial screen with the toggle on, should this be hidden when the multiple connections toggle is on?

Depends? This one is not moved to the modal, and since we said to hide the other two, I imagined we're keeping this part and morphing it to the Welcome screen. That info box will be included in the Welcome screen. Perhaps I got it wrong and it will be morphed into something else or discarded? Either way I separated the box so that it can be moved or copied to the new position later.

**Comment by kmruiz** [comment]
> > Screenshot 2024-03-12 at 11 23 47
> > This info box is visible in the initial screen with the toggle on, should this be hidden when the multiple connections toggle is on?
> 
> Depends? This one is not moved to the modal, and since we said to hide the other two, I imagined we're keeping this part and morphing it to the Welcome screen. That info box will be included in the Welcome screen. Perhaps I got it wrong and it will be morphed into something else or discarded? Either way I separated the box so that it can be moved or copied to the new position later.

That sounds a good approach, it works for me :D.

**Pull request merged**
