### PR TITLE
chore(deps): bump mongosh, kerberos, devtools-connect, etc

### PR DESCRIPTION
**Pull request by addaleax**
Currently fails with:

```js
@mongodb-js/compass-shell: ERROR in /home/addaleax/src/compass/node_modules/@mongosh/browser-repl/lib/mongosh-browser-repl.js
@mongodb-js/compass-shell: Module not found: Error: Can't resolve '@leafygreen-ui/code' in '/home/addaleax/src/compass/node_modules/@mongosh/browser-repl/lib'
@mongodb-js/compass-shell:  @ /home/addaleax/src/compass/node_modules/@mongosh/browser-repl/lib/mongosh-browser-repl.js 33:13712-13742
@mongodb-js/compass-shell:  @ ./src/components/compass-shell/compass-shell.jsx
@mongodb-js/compass-shell:  @ ./src/components/compass-shell/index.js
@mongodb-js/compass-shell:  @ ./src/plugin.js
@mongodb-js/compass-shell:  @ ./src/index.js
lerna ERR! npm run bootstrap exited 2 in '@mongodb-js/compass-shell'
```

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [ ] New feature
- [x] Dependency update
- [ ] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by gribnoysup** [comment]
I think adding `@leafygreen-ui/code` package changed the babel parser hoisting again and caused the issue described in this PR https://github.com/mongodb-js/compass/pull/2815

**Comment by gribnoysup** [comment]
Hmmm, looks like windows machine is not able to build `os-dns-native`:

```
npm ERR! code 1
npm ERR! path D:\a\compass\compass\node_modules\os-dns-native
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@5.1.1
npm ERR! gyp info using node@14.19.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.10 found at "C:\hostedtoolcache\windows\Python\3.9.10\x64\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v14.19.0/node-v14.19.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.19.0/node-v14.19.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v14.19.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v14.19.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v14.19.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v14.19.0/win-arm64/node.lib
npm ERR! gyp http 404 https://nodejs.org/download/release/v14.19.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.19.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.19.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.19.0/SHASUMS256.txt
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (D:\a\compass\compass\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at D:\a\compass\compass\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\a\compass\compass\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at D:\a\compass\compass\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at D:\a\compass\compass\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at D:\a\compass\compass\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at D:\a\compass\compass\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
npm ERR! gyp ERR! System Windows_NT 10.0.20348
npm ERR! gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\14.19.0\\x64\\node.exe" "D:\\a\\compass\\compass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\a\compass\compass\node_modules\os-dns-native
npm ERR! gyp ERR! node -v v14.19.0
npm ERR! gyp ERR! node-gyp -v v5.1.1
npm ERR! gyp ERR! not ok
```

**Comment by addaleax** [comment]
I don’t understand how this worked before then, honestly … the node-addon-api bump should not cause this kind of issue

**Comment by gribnoysup** [comment]
Maybe an issue with a GitHub windows machine then? 🤔

**Comment by addaleax** [comment]
Based on https://github.com/nodejs/node-gyp/issues/2462, a newer node-gyp version might resolve this, so I’ll try using npm 8 now which should come with that, and should be fine to use in CI

**Comment by gribnoysup** [comment]
RE the npm@8 update, if it doesn't break anything, we should be able to keep this change, the issue that originally required us to fix the version on a very particular 7 release was finally fixed I think (but also totally fine if we do it in a separate PR, there are probably some other places where we would want to clean up references to 7 anyway, just FYI sorta)

**Review by gribnoysup — APPROVED** [review]

**Pull request merged**
