### PR TITLE
chore(monorepo): Replace MongoDB 6.0.0-rc version with 6.0.0

### PR DESCRIPTION
**Pull request by gribnoysup**
Seems like rcs will be removed from the manifest based on [this](https://jira.mongodb.org/browse/CLOUDP-113091) and [this](https://mongodb.slack.com/archives/C0V896UV8/p1658301820234089) and anyway now that 6 is GA we probably want to explicitly use that in tests

### CODE REVIEW

**Review by lerouxb — APPROVED** [review]

**Comment by gribnoysup** [comment]
Hmm, seems like this actually broke some tests, will look more into it

**Comment by addaleax** [comment]
@lerouxb @gribnoysup I’ve updated the e2e tests to make use of the actual server version rather than the one gathered from the environment. The specific problem here was that we specified `6.x.x` in the environment, then for version checks replaced `x`es with `999` and so compared `6.999.999` with `6.1.0-alpha0` for columnstore support, rather than using the actual version `6.0.0`. Just generally speaking, it makes the tests a bit more self-contained in general not to rely on (potentially wrong) external information. We do runtime server version detection in mongosh as well for similar reasons.

**Comment by lerouxb** [comment]
It is the difference between what it is running against and what it is expecting to be running against, but I suppose it doesn't matter too much. I might have been overthinking it.

**Review by Anemy — APPROVED** [review]

**Comment by addaleax** [comment]
Okay, merged main again to see if that helps with CI, but at this point it’s just a wild guess; the e2e-coverage task is failing with segmentation faults in the mongodb-runner teardown script, although it should really not be affected at all by the version change here since it’s using 4.4.x anyway.

**Comment by gribnoysup** [comment]
Yeah, that's unexpected. Can it be something with the machine that is running tests maybe? Although this would probably not be consistently happening then, hmmmm 🤔

**Pull request merged**
