### PR TITLE
fix: Treat 304 as an ok response when downloading fonts

### PR DESCRIPTION
**Pull request by gribnoysup**

### CODE REVIEW

**Review by addaleax — APPROVED** [review]
I guess this is a (slightly preferable) alternative to #2344 ?

**Comment by gribnoysup** [comment]
Yeah, we just weren't sure if the issue was something easy to find/fix immediately so went for disabling cache altogether as a quick workaround in #2344

**Comment by mcasimir** [comment]
> I guess this is a (slightly preferable) alternative to #2344 ?

yep!

**Comment by gribnoysup** [comment]
[Evergreen patch](https://spruce.mongodb.com/task/10gen_compass_main_macos_oneshot_compile_test_package_publish_patch_12f32589e5e49ee341ab0f548ad78b751e16a3d1_60ec4341d6d80a7d5c0669e7_21_07_12_13_27_55/logs?execution=0) for macos

**Comment by gribnoysup** [comment]
Patch is green, merging

**Pull request merged**
