### PR TITLE
COMPASS-3991 Update to node driver 3.3.5

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

An interesting fact about switching to node driver 3.3.5 that data service was already on 3.3.5, so basically I updated the node version only for connection model and compass connect (that uses both data service and connection model as dependencies).

Node driver 3.3.5 release includes fixes for the unified topology:
https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.5

After switching to 3.3.5 one test failed in connection model. It happened because the server selection loop in node driver is now `30000ms` by default. And unit tests wait for results only during `2000ms`. To fix tests I explicitly set serverSelectionTimeoutMS to `1000ms`.

More about new unified topology is here:
https://mongodb.github.io/node-mongodb-native/3.3/reference/unified-topology/

Also, the format of the error from the driver was changed a little bit. Since driver retries to connect until it fails by timeout the type of the error will be always the timeout error. To provide extra information driver returns a new error property called `reason`. For example, in case of failures, the error message can be `MongoTimeoutError: Server selection timed out after 1000 ms` and error reason `Error: connect ECONNREFUSED 127.0.0.1:29384`.

### Checklist
- ~New tests and/or benchmarks are included~
- ~Documentation is changed or added~

## Motivation and Context

- [x] Dependency update

## Types of changes

- [x] Patch (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by imlucas** [comment]
@alenakhineika is this ready for review or waiting on something?

**Comment by alenakhineika** [comment]
@imlucas yes you can test it! please :)

**Comment by imlucas** [comment]
@alenakhineika happy to. I saw in slack this morning

> if you want to get back on that call we can discuss that issue you were looking into

Could you add some more context? Also, is there anything to watch out for in testing `3.3.5` node driver? Does it contain any particular changes we should pay attention to? (adding answers to any of these in the pull request description would be much appreciated!)

**Comment by alenakhineika** [comment]
@imlucas updated description! pls let me know if you have any questions or you want me to add some more info.

**Comment by imlucas** [comment]
@alenakhineika thank you! I'll test and send back info.


> To provide extra information driver returns a new error property called reason. For example, in case of failures, the error message can be MongoTimeoutError: Server selection timed out after 1000 ms and error reason Error: connect ECONNREFUSED 127.0.0.1:29384.

Oh! That's good to know. 🤔looking In #compass slack, being able to show "humanized" error messages would take a lot of burden off users and us to support would be a quick win. I've created https://jira.mongodb.org/browse/COMPASS-4009 Maybe we could chat in our next planning/triage with @mmarcon?

https://jira.mongodb.org/browse/COMPASS-3407

**Comment by alenakhineika** [comment]
@imlucas sounds good! 👍

**Pull request merged**
