### PR TITLE
chore(ci): fix snyk test hanging COMPASS-7947

### PR DESCRIPTION
**Pull request by mcasimir**
Tests only the production dependencies calling the snyk api. This should be needed only temporarily, while we replace it with the silk based system.

### CODE REVIEW

**Review by lerouxb — APPROVED** [review]

**Comment by addaleax** [comment]
Do you know why the test was hanging before?

> This should be needed only temporarily, while we replace it with the silk based system.

We'll still be using Snyk to scan dependencies, just to be clear

**Comment by mcasimir** [comment]
> Do you know why the test was hanging before?

On my machine it was taking hours on a couple of packages, it became really slow over time, not sure why, initially was only taking 10-20 minutes.

> We'll still be using Snyk to scan dependencies, just to be clear

Isn't that what Silk should be doing, getting vulnerabilities for dependencies and adding them to the sbom?

Happy to keep this code, in fact is much quicker and works so much better than the other alternative that we should probably just replace it in sbom-tools if it needs to stay.

**Comment by addaleax** [comment]
> Isn't that what Silk should be doing, getting vulnerabilities for dependencies and adding them to the sbom?

I agree that it _should_ be doing that, but it isn't. It's just going to integrate the vulnerabilities found through Snyk into the SBOM, but we still need to run the Snyk scanning ourselves. (I don't know _why_ this can't be simpler, no.)

**Comment by mcasimir** [comment]
>  we still need to run the Snyk scanning ourselves.

how do we report the vulnerabilities that we find?

**Comment by addaleax** [comment]
@mcasimir My understanding is that we use Snyk to discover vulnerabilities and then Silk's integration with Snyk will take care of augmenting the SBOM, creating JIRA tickets, etc.

**Pull request merged**
