### PR TITLE
Quick dark mode hack

### PR DESCRIPTION
**Pull request by mmarcon**
## Description

Given that dark mode is being requested a lot, I was wondering if it could be hacked together quickly. I stumbled upon https://github.com/darkreader/darkreader and it turns out that if are willing to accept that the result won't be a perfect color palette, we can do dark mode with just a few lines of code.

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context
- [ ] Bugfix
- [x] New feature
- [ ] Dependency update
- [ ] Misc

## Open Questions
* How do we toggle dark mode on and off?

## Types of changes

- [ ] *Backport Needed*
- [ ] Patch (non-breaking change which fixes an issue)
- [x] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

# Screenshots
image (2)
image (1)

### CODE REVIEW

**Comment by jirikrepl** [comment]
takemymoney

**Comment by durran** [comment]
How do we switch between the two modes?

**Comment by mmarcon** [comment]
Chatted with @fredtruman about this. We thought we'd add a "toggle experimental dark mode" somewhere in the OS menu (e.g. under View) and set a global class we could use in some plugins to tweak some specific styling, e.g. the sidebar bg color.

However, I just realized `darkreader.enable()` throws several exceptions in the console because it's trying to call `fetch()` on a bunch of files using the `file://` protocol, which breaks CORS. `try/catch` does not seem to help and passing `node-fetch` as the default fetch for darkreader does to help either as it does not like `file://`. This makes it a bit trickier than expected.

**Comment by jirikrepl** [comment]
Hi, it would be nice if someone can pick this up and finish it. Dark mode would be really great!

**Comment by janos-r** [comment]
Can't this be shipped as a plugin to toggle? I use darkreader all the time and I thought about this already in the past. Please add it to the official release so I can use it! You can add "(experimental)" to it or something. But it seams like a great compromise when not possible to ship a custom mode. This is the only app I have to run in light mode in my office, I have no idea why this was not a priority sooner.

**Comment by blueedgetechno** [comment]
Is it too much to ask for?

**Comment by Chidhambararajan** [comment]
guys who know electron a bit , just unpack the app.asar add the darkreader.js file , put a script tag in html which points to darkreader.js

and add the following lines to darkreader.js in the end of file 
```
function toggleDarkMode(){
    if(!DarkReader.isEnabled()){
        DarkReader.enable({
            brightness: 100,
            contrast: 90,
            sepia: 10
        });
    }else{
        DarkReader.disable();
    }
}
```
repack , then replace it with old app.asar

restart compass

Then in the menu bar , click View>Toggle Dev Tools
in the console just type toggleDarkMode();

That's the work around I'm going for..
While we wait for this pull request , this can be a quick work around max 15 mins I guess

Since most mongodb users have some basic understanding in javascript , this shoudl be easy

**Comment by jirikrepl** [comment]
Hi Devs, it would be great to have in as a next milestone!

**Comment by mmarcon** [comment]
Done in #2582.

**Pull request closed without merging**
