### PR TITLE
chore: remove plugin info plugin COMPASS-6009

### PR DESCRIPTION
**Pull request by gribnoysup**
This is just dead code clean up, this plugin is technically still accessible in the app, but we wanted to remove it for a while now

COMPASS-6009

### CODE REVIEW

**Review by addaleax — APPROVED** [review]

**Comment by addaleax** [comment]
Fwiw, the place where we discussed this before is the scope doc for the New Visual Brand project. We _do_ want to add logging for loading external plugins as a replacement for the plugins list (not just for errors), if we don’t do this in this PR, then we should create a follow-up ticket and address that soon-ish.

**Comment by gribnoysup** [comment]
Oh, I just assumed logging for plugin loading was added during the logging project already and haven't checked. Thanks for highlighting

**Comment by gribnoysup** [comment]
Maybe I'm misunderstanding, but seems like we have both logging and tracking for loading external plugins:

https://github.com/mongodb-js/compass/blob/536e2d248b7867ac99c2dec7b5d958f06860fa3c/packages/hadron-plugin-manager/lib/plugin-manager.js#L70-L71

Or do you mean something else?

**Comment by addaleax** [comment]
@gribnoysup I think we essentially just want to convert that `debug()` into a `log.info()` call :slightly_smiling_face:

**Comment by gribnoysup** [comment]
🤦 for some reason I assumed debug would also end up in the log, thanks for pointing this one out

**Review by addaleax — APPROVED** [review]

**Pull request merged**
