### PR TITLE
Add settings for editor

### PR DESCRIPTION
**Pull request by glucaci**
## Description
Add settings page for the editor which in this PR will include only the preference to set the default editor: `List`, `Json` or `Table`

This can be extended with options like:
- format of the UUID Encoding
- display options for Dates
- auto-expand all field on `Json` editor
- and much more...

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] I have signed the MongoDB Contributor License Agreement (https://www.mongodb.com/legal/contributor-agreement)

## Motivation and Context
- [x] New feature

## Types of changes
- [x] Minor (non-breaking change which adds functionality)

electron_B5ApYBNSP9

### CODE REVIEW

**Comment by Anemy** [comment]
Hi @glucaci - thanks for opening the pr!
We've been chatting about this as a team, and our inclination is to make it so that anytime the editor is opened it uses the last used editor setting; instead of a setting we always use the most recent. How does that sound to you? This would also be more easily integrated across products.

**Comment by glucaci** [comment]
Thank for update, it's sounds ok to me. I've introduced the editor settings page to can extend it with multiple other options which I've also listed. But I will open an issue for each of them to discus before I implement something.

So from the code point of view will be:
- remove settings page
- i think, move the settings from `UserConfigurablePreferences` to `InternalUserPreferences`
- change the settings every time editor state is changing

Let me know your thoughts.

**Comment by gribnoysup** [comment]
Preferences are compass-only feature as they require ability to write to disk and as we would like this to be browser-compatible and simplified for now, we want to avoid using preferences for this feature. What we were thinking of is a much simplified version of this:

- Last selected state of the view type is stored in the `localStorage` when user interacts with the swich and picked up from the `localStorage` when component is initially rendered

We use a [similar approach](https://github.com/mongodb-js/compass/blob/main/packages/databases-collections-list/src/use-view-type.tsx) for the `viewType` selector for the databases and collections list, although this one is persisted only using `sessionStorage` instead of `localStorage`

**Comment by mcasimir** [comment]
@glucaci we planned to implement this in an upcoming project, i will close this PR for now. Thanks for the suggestion!

**Pull request closed without merging**
