### PR TITLE
fix(explain-plan-model): include all child stages in iteration

### PR DESCRIPTION
**Pull request by addaleax**
This is part of SBE explain plan support, and something that I think
I genuinely just forgot to commit (something that we’ve just made
a lot harder, luckily :)).

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [ ] New feature
- [ ] Dependency update
- [x] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by gribnoysup — APPROVED** [review]
Looks good! Hope publishing is not a giant pain 🤞

**Comment by gribnoysup** [comment]
Yeah, maybe it's a good idea to wait for it to land if it's not too urgent

**Comment by gribnoysup** [comment]
Just wanted to say that I think the repo is in a good state now for this to be merged if you want to proceed. Release process for libraries is still manual, but other than that all CI stuff re tests and releasing compass should work okay. Also happy to go through the package release/version bump together (or even do it myself) if you feel like it

**Comment by addaleax** [comment]
> Also happy to go through the package release/version bump together (or even do it myself) if you feel like it

Yeah, let’s take some time for that tomorrow :)

**Pull request merged**
