### PR TITLE
COMPASS-3814: add respondTo ipc event to show info dialogue

### PR DESCRIPTION
**Pull request by lrlna**
## Description
Adds a new ipc event to be responded to: `showInfoDialog`. Can be used for any event, but is primarily created to show a message when schema is copied to clipboard at the moment. 

To use this new event:
```js
ipc.call('app:show-info-dialog', 'Message', 'Details string to show in the info dialogue')
```

## Motivation and Context
When sharing schema from `compass-schema`, it would not show the message box since `schema` plugin does not have access to the compass icon. This icon could have been moved to schema, but I figured it might be better if it's formulated as a reusable event.

- [x] Bugfix

## Dependents
Before merging this, we need [compass-schema#7](https://github.com/10gen/compass-schema/pull/7)

## Types of changes
- [x] Patch (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by durran** [comment]
I think this just needs an update to a new schema plugin and rebased. Then LGTM.

**Comment by lrlna** [comment]
will publish schema plugin and then merge this.

**Comment by lrlna** [comment]
@durran should i merge this branch into `1.20-releases` too?

**Comment by durran** [comment]
Yes I would put in the 1.20-releases branch as well.

**Comment by imlucas** [comment]
@lrlna [found it](https://travis-ci.community/t/npm-ci-will-fail-if-cached-dependency-includes-npm/4203/2)! good to go

**Comment by lrlna** [comment]
@imlucas ooooohhh cool! I've tried `npm cache clear --force` and everything and nothing worked. Good to know that's how you do it!

**Pull request merged**
