### PR TITLE
feat: uses a real password when builds a driverUrl

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

When a user clicks on a favorite, the connection string field is disabled as expected but then when the user clicks connect it does not work. It happens because a password is hidden in the field and parser uses starts instead of a proper password therefore auth fails. In the case of read-only URL use driverUrl that already saved for the current favorite instead of safeUrl.

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [x] Bugfix
- [ ] New feature
- [x] Dependency update
- [ ] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by mmarcon** [comment]
image

@fredtruman what copy could we put in that button? "Hide" does not sound right.

**Comment by fredtruman** [comment]
Hi there! I just checked out the branch to have a think about the HIDE terminology. Before I get there, I was curious about one thing. 

**Small thing:**
I noticed that if I change my port number from 27017 to 27016 on a localhost connect (and no other change) I get this _Incomplete key value pair for option_ which was unexpected ... no idea if that functionality is intended to be addressed later, or if I'm doing something wrong but just wanted to mention it:

Screenshot 2020-02-12 12 03 05

**HIDE**
In any event, to the topic at hand. I don't remember the HIDE button from previous versions, but with its introduction I think we've gone from ...
- [EDIT] >>> [SAVE CHANGES] or [DISCARD CHANGES]

... to:
- [EDIT] >>> [SAVE CHANGES] or [DISCARD CHANGES] or [HIDE NO CHANGES]

In the second case, [HIDE] is basically the same as [DISCARD CHANGES] just without any changeS to the connection string. With that in mind I think we have two (ideal) options: 

1. If we just want to leverage the EDIT button as the sole method for exposing plain text, we could consider:
- [EDIT] >>> [SAVE] or [CANCEL]
Where again, cancel is always available, with or without any change to the connection string in edit mode. HIDE isn't really necessary since I can only view if I'm in EDIT mode and the methods to get out of EDIT mode are only SAVE or CANCEL. This seems easiest to adapt from the current version.
Screenshot 2020-02-12 12 53 37


2. If we want to allow for SHOW / HIDE independently of EDITing the connection string, we should consider:
- [SHOW] >>> [HIDE]
- [EDIT] >>> [SAVE] or [CANCEL] 
Where cancel is always available, with or without any change to the connection string in edit mode.

Screenshot 2020-02-12 12 53 28

**Comment by alenakhineika** [comment]
@fredtruman it looks like in your connection sting you didn't specify a replicaSet value therefore you have this `Incomplete key value pair for option` syntax error:

mongodb://localhost:27016/?**replicaSet=**&readPreference=primary&appname=mongodb

**Comment by alenakhineika** [comment]
I don't see a big benefit from having show/hide buttons independent from the edit functionality. What could be a use case to just reveal your password without a possibility to edit or even see the whole connection string since the input is disabled? I like more the first concept. But do you think cancel/save buttons will be better than having links on the color background? Something like this:

Screenshot 2020-02-12 at 23 40 05

We can expand the use cases when we display these links. Eg to show the cancel link in case of a syntax error like this:

Screenshot 2020-02-12 at 23 46 58

Or in the case when URI was not changed:

Screenshot 2020-02-12 at 23 49 23

**Comment by fredtruman** [comment]
**Thanks Alena!** Ok, I see my URI was just bad, thanks for checking that!

**Re: Actions, etc.**
Yeah the independent HIDE / SHOW may not be necessary, so you're right the other pattern may be the easiest and most sensible thing to do here.

I think I prefer the buttons over the links in the banner just overall from an interaction pattern perspective. If a user has chosen to EDIT I believe they would expect to have the relevant actions to follow up SAVE / CANCEL immediately and always available, and I think the buttons reinforce that expectation. 

The banner is only displayed if there is a detected change, is that right? If a user wants to view their plain text connection URI, has chosen EDIT, makes no change to the connection URI, and then wants to obfuscate the password again, how would they access the CANCEL if the banner doesn't appear? 🤔

**Comment by mmarcon** [comment]
I added this to the agenda of today's design sync.

**Comment by imlucas** [comment]
Is this still WIP?

**Comment by alenakhineika** [comment]
@imlucas I think this PR can be closed. The following PR includes a new version of `compass-connect` with improved functionality:
https://github.com/mongodb-js/compass/pull/1908

**Pull request closed without merging**
